var f = function(){throw "error"; return "exit";};
try{f()}catch(e){print(e);}
